# Generated by Django 5.1.7 on 2025-07-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('service', models.CharField(choices=[('hotel_staffing', 'توفير عمالة فندقية'), ('training_programs', 'برامج تدريبية'), ('consulting', 'استشارات وحلول'), ('partnership', 'شراكة وتعاون'), ('other', 'أخرى')], max_length=50)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
