# Generated by Django 5.1.7 on 2025-07-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='phone',
        ),
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(upload_to='cvs/'),
        ),
    ]
