BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXX XX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX
  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXX XX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXX XXXXXXXXX XX
  XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XX
  XXXXXXXBBBBB BBBBBXXXXX XXXXXXXBBBBBBBBXXXXXXXX

  XXXX XXXXXX XXXXX XXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

  XXXX XXXXXX XXXXXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
  XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXXXX
XXXXXX

  XXXX X XXXXXX XXXX XXXXXXX XXXXXXX XXX
  XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
    XXXXXXXXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXX XXXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
    XXXXXXXX XXX
    XX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXX
      XX XXXXXXBBB BBBBBBXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXX XXXXXX  XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXXXX
      XXXX
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXXX XXXXXXXXXX XXXXXXX
        XX XXXXXXBBB BBBBBBX XXXXXXXBB BBBBBBBBBBBB BB BBBXXXXXXBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBX XXXXXXXBB BBBBBBBBBBBB BB BBBBBBBBBBXXXXXXBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXX XX XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBX XXXXXXXBB BBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBX XXXXXXXBB BBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBX XXXXXXXBB BBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBX XXXXXXXBB BBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXXXXX

  XXXX XXXX XXXXXXX XXX
  XXXXXX
    BBBBB BBBBBBBBBBBBBBB
  XXXXXXX

  XXXX XXXXXX XXX
  BBBBBBB BBBBBBBBBBBBBBBBBBB
XXXXXXX
XXXXXXX