BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBXX XXXXXXX X XXXXXXX XXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXX XXXXXXXXX XXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXX XXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXX
      X XX XXXXX XXXXXX XXXXX
    XXXXX
    XX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXX XXXXXXXXXXX XXXXXXX
      XXXXX XXXXXXX XXXXX XXXXX XXXXX XXXX XXXXXXX
    XXXX
  XXXXXX

  XXXX XXXX XXXXXXX XXX XXXXXXX X XX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXX XXXXX
  XX

    XXXX XXXXXXX XXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
      XXXXX X X XXXXXX
      XXXXXXXXXXX XXXXXXXX
      XXXXXXXXXXXXXX XXXXX
      XXXXXXXX XXXX XXXXX
      XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXX
    X XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXX XXXXX XXX X XXXXXXXXXXX

      XX XXXXXXXXXXX XXXXXXXXXXXXXX XXXX XX XXXXXX XXXXX XXXXXXXXXX XXXXXXXXX
        XXX XX XXXX XX XXXX XXXXX XXXXX XXXXXXX XXXXXX XXX XXXXX XX XXXXXXXX XXX XXXX XX XXXX XX XXXXXXX XXXXX XXXXXX XXXXXXX XXXXX XXXX XXXXX XX XXXXXX XXXXX XXXXX XXXXXX XXXX XXXXX XXXXXXXX XXXXXX XXXXXX XXXXX
      XXXX

      XX XXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXX
        XX XXXXXXXXX XXXXX XXX XXXXXX XXXXXXX XXX XXXXX XXXXXX XX XXXXXX XXXXXXXXXX XXXXX XXXXXX XX XXXXXXXXXXXXX XXX XXXXXXX XX XXXXXXXX XXXXXXXXX XXX XXXXXXX XXXXX XX XXXXXXXX XX XXXX XXXXXXX XX XXXXXXX XXX XXXXXXXXXX XXXXXXXXX
      XXXX
    XXXXXX

    XXXX XX XXX XXX
    XXXX XXXXXXX
      XXXXX X X XXXXXX
      XXXXXXXXXXX XXXXXX
      XXXXXXXXXXXXXX XXXXX
      XXXXXXXX XXXXX
      XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXX
      XXXXXXXXXXX XXXXXXX
    X XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
           XXXXXXX XXXXX
           XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXX XXXXXXX
        XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX
    XXXXXX
  XXXXXX

  XXXX XXXX XXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBX XXXXXXXXXXXXXXXXXXXXX
      X XXXXXX XXXXXXXX X XXXX XX XXXXXXXX
    XXXX
  XXXXXX
XXXXXX

XXXX XXXXXX XXX
XXXXXXX
  XXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX
  X

  XXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX
  X

  XXXX X
    XXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXXX
  X

  XXXX X
    XXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXX
  X

  XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXX X
    XXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXX XXXXXXX
      XXXXXXXXXXXX XXXXXXX
    X
  X
XXXXXXXX

XXXX XXX XXXX XXX
XXXXXXXX
  XXXXXXXXXX XXXXX XXXX XXX
XXXXXXXXX
BBBBBBBB
