BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBXXXXX XXXXXXX X XXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX

XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBX XXXXXXXXXXXXXXXXXXXX
        X XXXXXX X XXXX XX XXXXXXXX
      XXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXX
        X XXXXXX XXXXXXXX X XXXXXX X XXXXXXX
      XXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX

XXXXXXX
  XXXXXXXX X
    XXXXXXXX XX
    XXXXXXXXXX XXXXXXXX XX XXXXXXXXXXX XXXXXXXXX
  X

  XXXXXXXXXX XXXXXXXX X
    XX X XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXX X
    XXXX X XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXX X
  X

  XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXXXX XXXXX XXXX XXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXXX
    XXXXXXXXX XXXXXXX
    XXXXXXXXX XXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XXXXXXX
    XXXXX XXXXXXX
    XXXXXX XXXXXX
    XXXXXXX XXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXXX XX
    XXXXXXXXXX XXXXXXXXXX XX XXXXXXXXXXX XXXXXXXXX
  X

  XXXXXXXXXX XXXXXXXXXX X
    XX X XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX X
    XXX X XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX X
    XXXX X XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX X
  X

  XXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXXXXXX XX
    XXXXXXXXXX XXXXXXX
    XXXXXXX XXXXX
  X

  XXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXXX
  X

  XXXXXXXXXX XX X
    XXXXXXX XX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXX XXX XXX XXX XXXXXXXXXXXXXXXXX
  X

  XXXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
  X

  XXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXXX
    XXXXXXXXXXX XXX XXXX XXXXXXXXXXXX
  X

  XXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX
  X

  XXXXXXXXXXXX X
    XXXXXXX XXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXX XXXXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXX
  X
XXXXXXXX
BBBBBBBB
