BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBXXX XXXX X XXXXX XXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX X XXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXX XX XXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX
    XXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XX XXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXXXXXXXX XXXXXXX
        X XX XXX X XXXXXXXXXX XXX XXXXXXXXXXX XXXXX XXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXX
      XXXX
      XX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXX
        X XXX XXXX XXXX XXX XXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXX XX XXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXX
      XXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXX XXXX XXXXX XXXXXXXXXXX XXXXXXX
      XX XXXXXXBBB BBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXX XXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XX XXX XXXXXXXXX

      XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXX XXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXX XXXXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX

XXXXXXX
  XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXX
  X

  XXXXXXXXXX XXXXXXX X
    XX X XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXX X
    XXXX X XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXX X
  X

  XXXXXXXXXX XXXXXX X
    XX X XXXXXXXX XX X
    XXXX X XXXXXXXX XX X
  X

  XXXXXX XXXXXXXXXXX XXXXXX X
    XXXXXXXXXXXXXXX X
      XXXXXXXX XXXX XXXXX
    X
    XXXX X
      XXXXXXXX XXXX XXXXX
      XXXXXXXXXX XXXXX
    X
    XX X
      XXXXXXXXXX XXXXXX XXXXXXXXXXX
    X
  X
XXXXXXXX
BBBBBBBB
